config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :events do
    resources :reservations, only: [:new, :create]
    member do
      post 'register'
    end
  end

  resources :reservations, only: [:index, :new, :update] do
    member do
      patch 'validate'
      get 'validate'
    end
  end

  get 'myevents', to: 'myevents#index', as: 'my_events'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_one_attached :image
  validates :name, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :date_time, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations, dependent: :destroy
  has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :name])

    # For additional fields in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @events = Event.all
    if params[:query].present?
      @events = @events.where("location ILIKE ?", "%#{params[:query]}%")
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to @event, notice: 'L\'événement a été créé avec succès.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'L\'événement a été mis à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    if @event.user == current_user
      @event.destroy
      redirect_to events_path, notice: 'Événement supprimé avec succès.'
    else
      redirect_to events_path, alert: 'Vous n\'êtes pas autorisé à supprimer cet événement.'
    end
  end

  def register
    @event = Event.find(params[:id])
    current_user.reservations.create(event: @event)
    redirect_to @event, notice: "Vous êtes maintenant inscrit à cet événement."
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :date_time, :location, :address, :open, :image)
  end
end

app/controllers/myevents_controller.rb
class MyeventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = current_user.events
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @events = Event.order(created_at: :desc).limit(6)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:update, :validate]
  before_action :authenticate_user!

  def index
    @reservations = current_user.reservations
  end

  def new
    @event = Event.find(params[:event_id])
    @reservation = @event.reservations.build
  end

  def create
    @event = Event.find(params[:event_id])
    @reservation = @event.reservations.build(reservation_params)
    @reservation.user = current_user
    if @reservation.save
      redirect_to reservations_path, notice: 'La réservation a été créée avec succès.'
    else
      render :new
    end
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to reservations_path, notice: 'La réservation a été mise à jour avec succès.'
    else
      render :edit
    end
  end

  def validate
    @reservation.update(status: "validated")
    redirect_to reservations_path, notice: 'La réservation a été validée avec succès.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_card.html.erb
<div class="container">
  <div class="row">
    <% @events.each do |event| %>
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card-evt">
          <%= link_to event_path(event) do %>
            <% if event.image.attached? %>
              <%= cl_image_tag(event.image.key, class: "card-img-top evt-profile-img") %>
            <% end %>
            <div class="card-body">
              <h1 class="card-title"><%= truncate(event.name, length: 52) %></h1>
              <h2 class="card-text"><%= truncate(event.description, length: 85) %></h2>
              <div class="card-location">
                <p>📍<%= event.location %></p>
              </div>
              <div class="evt-date">
                <p><%= event.formatted_date %></p>
              </div>
            </div>
            <div class="card-footer">
              <h3 class="card-fiesta"><%=event.open ? "S'inscrire" : "complet" %></h3>
              
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_card_fiesta.html.erb
 <div class="row">
    <% @events.each do |event| %>
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="p-4 card-fiesta">
          <% if event.image.attached? %>
            <%= cl_image_tag(event.image.key, class: "img-fluid", style: 'border-radius: 5px;') %>
          <% end %>

          <div class="card-fiesta-infos">
            <div>
              <h2><%= event.name %></h2>
              <p><%= event.address%></p>
              <p><%= event.description%></p>
              <p><strong> Organisateur :</strong> <%= event.user.name %> <%= event.user.firstname %></p>
              <%= link_to 'Voir les détails', event_path(event), class: 'button', style: 'padding: 6px 12px; font-size: 14px; margin-top: 30px;' %>
            </div>
            <h3 class="card-fiesta-"><strong> Ouvert :</strong> <%= event.open ? 'Oui' : 'Non' %></h3>
            <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-fiesta-user avatar-bordered" />
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/events/_form.html.erb
<%= simple_form_for @event do |form| %>
  <%= form.error_notification %>

  <div class="alert alert-danger" id="alert-missing-fields" style="display: none;">
    Veuillez remplir tous les champs obligatoires.
  </div>

  <div class="form-inputs mt-4">
    <%= form.input :name, label: "Nom", input_html: { class: 'field-bg-color field-no-border', placeholder: "nom de l'évènement" } %>
    <%= form.input :location, label: "Adresse", input_html: { class: 'field-bg-color field-no-border', placeholder: "Adresse de l'évènement" } %>
    <%= form.input :description, input_html: { class: 'field-bg-color field-no-border', placeholder: "Description de l'évènement" } %>
    <%= form.input :date_time, label: "Date & heure", input_html: { class: 'field-bg-color field-no-border', value: @event.date_time.try(:strftime, '%Y-%m-%d %H:%M'), placeholder: "Date et heure de l'évènement" }, wrapper_html: { class: 'mb-3' }, html5: true %>
    <%= form.input :image, as: :file, input_html: { class: 'field-bg-color field-no-border' } %>
    <%= form.hidden_field :open, value: true %>
  </div>

  <div class="form-actions text-end">
    <%= link_to 'Retour', events_path, class: 'btn btn-secondary' %>
    <%= form.button :submit, "Créer l'évènement", class: 'btn btn-primary', onclick: 'return validateForm();' %>
  </div>
  <p>Les champs marqués d'un <b>*</b> sont obligatoires</p>
<% end %>

<script>
  function validateForm() {
    var name = document.getElementById('event_name').value;
    var location = document.getElementById('event_location').value;
    var description = document.getElementById('event_description').value;
    var dateTime = document.getElementById('event_date_time').value;

    if (name === '' || location === '' || description === '' || dateTime === '') {
      document.getElementById('alert-missing-fields').style.display = 'block';
      return false; // Empêche l'envoi du formulaire
    }

    return true; // Permet l'envoi du formulaire si tout est rempli
  }
</script>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 mt-">
      <h1 class="h1-line">Edit the event <u><%= @event.name %></u></h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <h1 class="my-4" style="font-family: 'Bebas Neue', sans-serif; font-weight: 400; font-style: normal; font-size: 80px;">
    Tous nos Events
  </h1>
</div>

<div class="index-top-card mt-4 p-4 mb-5" style="background-image: url('<%= asset_path('index_image.jpg') %>'); background-size: cover; background-position: center;">
  <div class="container custom-height d-flex justify-content-center align-items-center">
    <div id="cover">
      <%= form_with url: events_path, method: :get, class: "d-flex" do %>

          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Chercher par ville"
          %>
          <div class="td" id="s-cover">
          <%= submit_tag "Go!", name: "", id: "s-circle", class: "btn gradient-text" %>
          </div>

      <% end %>
    </div>
  </div>
</div>


<!-- Fiestas Grid -->
<div class="container mt-5">
  <%= render 'card' %>
</div>

app/views/events/new.html.erb
<% content_for :body_class, "show-page" %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10 col-md-6 mt-4">
      <h1 style="font-family:Bebas Neue, sans-serif; font-weight: 400; font-style: normal; font-size: 80px;">Crées ton événement!</h1>
    </div>
    <div class="col-md-6 mt-1 new-card" style="position: relative;">
      <div class="background-container"></div>
      <div class="content-container">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% content_for :body_class, "show-page" %>

<div class="container">
  <h1 class="mt-4" style="font-family:Bebas Neue, sans-serif;font-weight:400;font-style:normal;font-size:80px;">
    Détail de l'événement
  </h1>
  <div class="row justify-content-center">
    <div class="col-lg-10 col-md-6 col-12 mb-4 p-4">
      <div class="card-top d-flex align-items-center mx-auto mt-5">
        <% if @event.image.attached? %>
          <%= cl_image_tag(@event.image.key, class: "image") %>
        <% end %>
        <div class="event-infos flex-grow-1 p-2 position-relative">
          <h1 class="gradient-text"><strong><%= @event.name %></strong></h1>
          <p>Une phrase pour décrire votre événement : <br>
          <strong><%= @event.description %></strong></p>
          <p><strong>Ouvert :</strong> <%= @event.open ? 'Oui' : 'Non' %></p>
          <p><strong>Date et heure :</strong> <%= @event.date_time ? @event.date_time.strftime("%d/%m/%Y %H:%M") : "Non spécifiée" %></p>
          <p><strong>Organisateur :</strong> <%= @event.user.name %> <%= @event.user.firstname %></p>

          <% if current_user.reservations.exists?(event: @event) %>
            <p class="button">Déjà réservé!</p>
          <% else %>
            <%= form_with(url: register_event_path(@event), method: :post) do |form| %>
              <%= form.submit "Réserver ma place", class: "button", style: 'border-radius:5px; margin-top: 15px;' %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="card-middle d-flex align-items-center justify-content-center mx-auto p-4">
        <h2 class="text-center gradient-text">Adresse :<br>
        <strong><%= @event.location %></strong></h2>
      </div>

      <div class="button-container d-flex justify-content-end mt-3">
        <a href="<%= events_path %>" class="btn btn-secondary mt-3">Retour à la liste</a>
        <% if @event.user == current_user %>
          <%= form_with url: event_path(@event), method: :delete, class: 'd-inline' do %>
            <%= submit_tag "Supprimer l'évènement", class: 'btn btn-danger mt-3 ms-2' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airfiestas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AirFiestas</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="data:image/x-icon;" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  </head>
  <body class="background-white <%= yield :body_class %>">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/myevents/index.html.erb
<div class="container">
  <h1 class="mt-4" style= "font-family:Bebas Neue, sans-serif;font-weight:400;font-style:normal;font-size:80px;">Mes évènements</h1>
  <%= render 'events/card' %>
</div>

app/views/pages/home.html.erb
<!-- Banner -->

<div class="banner mt-4 p-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.1)), url(https://www.civitatis.com/blog/wp-content/uploads/2023/05/festivales-musica-mas-esperados-verano.jpg);">
  <div class="container">
    <div class="row justify-content-center align-items-center";>
      <div class="col-10 col-md-6 text-center">
        <%= image_tag asset_path('AIR FIESTAS font style 250p.png'),style:"height:110px; margin-bottom: 10px; padding: 0;" %>
        <h2 style="margin-bottom: 60px;">La plateforme pour créer et réserver des soirées </h2>
        <%= link_to 'Voir toutes les soirées  🎉', events_path, class: 'button nav-link', style:"font-size:25px" %>
      </div>
    </div>
  </div>
</div>

 <!-- Fiestas Grid -->

<div class="container">
  <h1 class="my-4" style= "font-family:Bebas Neue, sans-serif;font-weight:400;font-style:normal;font-size:80px;">
  Soirées à la une!</h1>
  <%= render 'events/card' %>
</div>


<!-- Fiestas Footer in the layout -->


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

app/views/reservations/_reservation-card.html.erb
<div class="row">
  <% @reservations.each do |reservation| %>
    <div class="col-lg-4 col-md-6 mb-4">
      <%= link_to event_path(reservation.event), class: '' do %>
        <div class="first evt">
          <% if reservation.event.image.attached? %>
            <%= cl_image_tag(reservation.event.image.key, class: "evt-profile-img") %>
          <% end %>
          <div class="evt-description-bk"></div>
          <p><%= reservation.event.name %></p>
          <div class="evt-description">
            <p><%= reservation.event.name %></p>
          </div>
          <div class="evt-date">
            <p><i class="fa-solid fa-location-dot"></i> <%= reservation.event.location %></p>
            <p><i class="fa-solid fa-calendar-days"></i> <%= I18n.l(reservation.event.date_time, format: :short) %></p>
          </div>
          <div class="evt-btn">
            <h3 class="card-fiesta"><%= reservation.event.open ? 'Places disponibles' : 'Complet' %></h3>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/reservations/index.html.erb
<div class="container">
  <h1 class="mt-4 mb-4" style= "font-family:Bebas Neue, sans-serif;font-weight:400;font-style:normal;font-size:80px;">Mes réservations</h1>
  <% if @reservations.any? %>
     <%= render 'reservation-card' %>
</div>
  <% else %>
    <p class="text-center">Vous n'avez pas encore de réservations.</p>
  <% end %>
</div>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

app/views/reservations/validate.html.erb
<h2>Page de validation</h2>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer ">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Fiestas organisées avec <i class="fas fa-heart"></i> pour votre pur bonheur...
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid d-flex justify-content-between align-items-center align-items-center custom-max-width">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag asset_path('LOGO AIR FIESTAS.png'), style:"width:100px;border-radius: 20px" %>
    <% end %>

    <div class="d-flex justify-content-end align-items-center flex-grow-1 align-items-center">
      <ul class="navbar-nav align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mes réservations", reservations_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mes évènements", my_events_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Ajouter un évènement", new_event_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar nav-link" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://i.postimg.cc/zBMBVHnG/man.png", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Se déconnecter", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>